-- Generated by tools/generate.py. slot_data key -> tracker setting.
SLOT_CODES = {
	enable_hidden_packages = {
		code = "enable_hidden_packages",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	enable_rampages = {
		code = "enable_rampages",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	enable_stunt_jumps = {
		code = "enable_stunt_jumps",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	enable_emergency_vehicles = {
		code = "enable_emergency_vehicles",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	enable_properties = {
		code = "enable_properties",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	enable_robbable_stores = {
		code = "enable_robbable_stores",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	enable_side_events = {
		code = "enable_side_events",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	shuffle_emergency_rewards = {
		code = "shuffle_emergency_rewards",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	randomize_radio_stations = {
		code = "randomize_radio_stations",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	shuffle_minimap = {
		code = "shuffle_minimap",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	randomize_pickups = {
		code = "randomize_pickups",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	split_mainland_access = {
		code = "split_mainland_access",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	death_link = {
		code = "death_link",
		mapping = { [0] = 0, [1] = 1, [false] = 0, [true] = 1 },
	},
	goal = {
		code = "goal",
		mapping = {
			["final_mission"] = 0, [0] = 0,
			["hidden_packages"] = 1, [1] = 1,
			["hundred_percent"] = 2, [2] = 2,
		},
	},
}

-- Set-valued slot_data keys: member key -> the setting it turns on.
SLOT_SET_CODES = {
	ability_locks = {
		["crouch"] = "ability_lock_crouch",
		["jump"] = "ability_lock_jump",
		["sprint"] = "ability_lock_sprint",
		["vehicles"] = "ability_lock_vehicles",
		["wallet"] = "ability_lock_wallet",
		["weapon_equip"] = "ability_lock_weapon_equip",
	},
	content_locks = {
		["hidden_packages"] = "content_lock_hidden_packages",
		["properties"] = "content_lock_properties",
		["rampages"] = "content_lock_rampages",
		["robbable_stores"] = "content_lock_robbable_stores",
		["stunt_jumps"] = "content_lock_stunt_jumps",
	},
}

-- The game's own completion percentage: the item its number is
-- drawn on, and the AP data store key the client publishes it
-- under, one per team and slot.
PERCENTAGE_CODE = "Percentage Completed"
PERCENTAGE_KEY_PREFIX = "gta_vice_city_percentage_"
