-- Generated by tools/generate.py from the GTA Vice City apworld.
-- One function per AP location returning its PopTracker AccessibilityLevel:
-- its region entry ANDed with the world's own requirements for it. A rule
-- that differs between the properties class being on and off carries both
-- and switches on the seed's own setting.

function rule_An_Old_Friend() return reachAccess(true) end
function rule_The_Party() return reachAccess(has("Progressive Rosenberg")) end
function rule_Back_Alley_Brawl() return reachAccess(itemAtLeast("Progressive Rosenberg", 2)) end
function rule_Jury_Fury() return reachAccess(itemAtLeast("Progressive Rosenberg", 3)) end
function rule_Riot() return reachAccess(itemAtLeast("Progressive Rosenberg", 4)) end
function rule_Treacherous_Swine() return reachAccess(has("Progressive Cortez")) end
function rule_Mall_Shootout() return reachAccess(itemAtLeast("Progressive Cortez", 2)) end
function rule_Guardian_Angels() return reachAccess(itemAtLeast("Progressive Cortez", 3)) end
function rule_Sir_Yes_Sir() return reachAccess(itemAtLeast("Progressive Cortez", 4)) end
function rule_All_Hands_On_Deck() return reachAccess(itemAtLeast("Progressive Cortez", 5)) end
function rule_The_Chase() return reachAccess((has("Starfish Island Access") and has("Progressive Diaz"))) end
function rule_Phnom_Penh_86() return reachAccess((has("Starfish Island Access") and itemAtLeast("Progressive Diaz", 2))) end
function rule_The_Fastest_Boat() return reachAccess((has("Starfish Island Access") and itemAtLeast("Progressive Diaz", 3) and lockTerm("Sea Vehicles", "ability_lock_vehicles"))) end
function rule_Supply_Demand() return reachAccess((has("Starfish Island Access") and itemAtLeast("Progressive Diaz", 4) and lockTerm("Sea Vehicles", "ability_lock_vehicles"))) end
function rule_Rub_Out() return reachAccess((has("Starfish Island Access") and itemAtLeast("Progressive Diaz", 5) and has("Progressive Death Row"))) end
function rule_Death_Row() return reachAccess(has("Progressive Death Row")) end
function rule_Four_Iron() return reachAccess(has("Progressive Avery")) end
function rule_Two_Bit_Hit() return reachAccess(itemAtLeast("Progressive Avery", 2)) end
function rule_Demolition_Man() return reachAccess((itemAtLeast("Progressive Avery", 3) and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Gun_Runner() return reachAccess((has("Mainland Access") and has("Progressive Phil Cassidy"))) end
function rule_Boomshine_Saigon() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Phil Cassidy", 2))) end
function rule_Shakedown() return reachAccess((has("Starfish Island Access") and has("Progressive Vercetti Protection"))) end
function rule_Bar_Brawl() return reachAccess((has("Starfish Island Access") and itemAtLeast("Progressive Vercetti Protection", 2))) end
function rule_Cop_Land() return reachAccess((has("Starfish Island Access") and itemAtLeast("Progressive Vercetti Protection", 3))) end
function rule_Alloy_Wheels_of_Steel() return reachAccess((has("Mainland Access") and has("Progressive Big Mitch Baker"))) end
function rule_Messing_with_the_Man() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Big Mitch Baker", 2))) end
function rule_Hog_Tied() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Big Mitch Baker", 3))) end
function rule_Stunt_Boat_Challenge() return reachAccess((has("Mainland Access") and has("Progressive Umberto Robina") and lockTerm("Sea Vehicles", "ability_lock_vehicles"))) end
function rule_Cannon_Fodder() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Umberto Robina", 2))) end
function rule_Naval_Engagement() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Umberto Robina", 3))) end
function rule_Trojan_Voodoo() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Umberto Robina", 4))) end
function rule_Juju_Scramble() return reachAccess((has("Mainland Access") and has("Progressive Auntie Poulet"))) end
function rule_Bombs_Away() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Auntie Poulet", 2))) end
function rule_Dirty_Lickin_s() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Auntie Poulet", 3))) end
function rule_Love_Juice() return reachAccess((has("Mainland Access") and has("Progressive Love Fist"))) end
function rule_Psycho_Killer() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Love Fist", 2))) end
function rule_Publicity_Tour() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Love Fist", 3))) end
function rule_Road_Kill() return reachAccess(has("Progressive Mr. Black")) end
function rule_Waste_the_Wife() return reachAccess(itemAtLeast("Progressive Mr. Black", 2)) end
function rule_Autocide() return reachAccess(itemAtLeast("Progressive Mr. Black", 3)) end
function rule_Check_Out_at_the_Check_In() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Mr. Black", 4))) end
function rule_Loose_Ends() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Mr. Black", 5))) end
function rule_Cap_the_Collector()
	if propertiesEnabled() then
		return reachAccess((has("Mainland Access") and has("Progressive Vercetti Finale") and itemAtLeast("Progressive Vercetti Protection", 3) and has("Printworks Ownership") and itemAtLeast("Progressive Printworks", 2) and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties") and satisfiedCount({(has("Malibu Club Ownership") and itemAtLeast("Progressive Malibu Club", 4) and lockTerm("Land Vehicles", "ability_lock_vehicles")), (has("Film Studio Ownership") and itemAtLeast("Progressive Film Studio", 4) and lockTerm("Air Vehicles", "ability_lock_vehicles") and lockTerm("Land Vehicles", "ability_lock_vehicles")), (has("Kaufman Cabs Ownership") and itemAtLeast("Progressive Kaufman Cabs", 3)), (has("Cherry Popper Ownership") and has("Progressive Cherry Popper")), (has("Boatyard Ownership") and has("Progressive Boatyard") and lockTerm("Sea Vehicles", "ability_lock_vehicles")), (has("Sunshine Autos Ownership") and lockTerm("Land Vehicles", "ability_lock_vehicles")), has("Pole Position Ownership")}) >= 5))
	else
		return reachAccess((has("Mainland Access") and has("Progressive Vercetti Finale") and itemAtLeast("Progressive Vercetti Protection", 3) and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties")))
	end
end
function rule_Keep_Your_Friends_Close()
	if propertiesEnabled() then
		return reachAccess((has("Starfish Island Access") and itemAtLeast("Progressive Vercetti Finale", 2) and itemAtLeast("Progressive Vercetti Protection", 3) and has("Mainland Access") and has("Printworks Ownership") and itemAtLeast("Progressive Printworks", 2) and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties") and satisfiedCount({(has("Malibu Club Ownership") and itemAtLeast("Progressive Malibu Club", 4) and lockTerm("Land Vehicles", "ability_lock_vehicles")), (has("Film Studio Ownership") and itemAtLeast("Progressive Film Studio", 4) and lockTerm("Air Vehicles", "ability_lock_vehicles") and lockTerm("Land Vehicles", "ability_lock_vehicles")), (has("Kaufman Cabs Ownership") and itemAtLeast("Progressive Kaufman Cabs", 3)), (has("Cherry Popper Ownership") and has("Progressive Cherry Popper")), (has("Boatyard Ownership") and has("Progressive Boatyard") and lockTerm("Sea Vehicles", "ability_lock_vehicles")), (has("Sunshine Autos Ownership") and lockTerm("Land Vehicles", "ability_lock_vehicles")), has("Pole Position Ownership")}) >= 5))
	else
		return reachAccess((has("Starfish Island Access") and itemAtLeast("Progressive Vercetti Finale", 2) and itemAtLeast("Progressive Vercetti Protection", 3) and has("Mainland Access") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties")))
	end
end
function rule_Hidden_Package_Ocean_Beach_1() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_1() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Viceport_1() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Viceport_2() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Viceport_3() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Viceport_4() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Viceport_5() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Washington_Beach_1() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Washington_Beach_2() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_2() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_3() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Washington_Beach_3() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_4() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_5() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_6() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_7() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_8() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_9() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_10() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_11() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_12() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_13() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_14() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_15() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_16() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_17() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Starfish_Island_1() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Starfish_Island_2() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_18() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_19() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Viceport_6() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Viceport_7() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Viceport_8() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_1() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Vice_Point_20() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_21() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_22() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_23() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_24() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_25() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Leaf_Links_1() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Downtown_1() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Leaf_Links_2() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Downtown_2() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Downtown_3() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Leaf_Links_3() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Vice_Point_26() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Little_Havana_2() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Prawn_Island_1() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Prawn_Island_2() return reachAccess(lockTerm("Hidden Packages", "content_lock_hidden_packages")) end
function rule_Hidden_Package_Starfish_Island_3() return reachAccess((has("Starfish Island Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_3() return reachAccess((has("Starfish Island Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_4() return reachAccess((has("Starfish Island Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Starfish_Island_4() return reachAccess((has("Starfish Island Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Starfish_Island_5() return reachAccess((has("Starfish Island Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Downtown_4() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Downtown_5() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Downtown_6() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Downtown_7() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Downtown_8() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Downtown_9() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Downtown_10() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Haiti_1() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Haiti_2() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Haiti_3() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Haiti_4() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Haiti_5() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Haiti_6() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Haiti_7() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_5() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_6() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_7() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_8() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_9() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_10() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_1() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_11() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_2() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Viceport_9() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Viceport_10() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_3() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_4() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Viceport_11() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_5() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_6() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_7() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_8() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_9() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_10() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_11() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_12() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_13() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_14() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_15() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_16() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_12() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_13() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Little_Havana_14() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_17() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Hidden_Package_Escobar_International_18() return reachAccess((has("Mainland Access") and lockTerm("Hidden Packages", "content_lock_hidden_packages"))) end
function rule_Tear_Gas_Rampage_Ocean_Beach() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Rocket_Launcher_Rampage_Escobar_International() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_MP5_Rampage_Vice_Point_1() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Tec_9_Rampage_Vice_Point() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Rocket_Launcher_Rampage_Vice_Point() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Ruger_Rampage_Vice_Point() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Flamethrower_Rampage_Downtown() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_MP5_Rampage_Downtown() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Tear_Gas_Rampage_Downtown() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_M60_Rampage_Little_Haiti() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Mac_10_Rampage_Little_Havana() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Chainsaw_Rampage_Washington_Beach() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_308_Sniper_Rampage_Ocean_Beach() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Rampage_Little_Havana() return reachAccess((has("Starfish Island Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_357_Rampage_Escobar_International() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Rocket_Launcher_Rampage_Viceport() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Minigun_Rampage_Little_Havana() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Grenade_Rampage_Escobar_International() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Sniper_Rifle_Rampage_Little_Havana() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Katana_Rampage_Washington_Beach() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Rampage_Ocean_Beach() return reachAccess((lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Pistol_Rampage_Vice_Point() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_MP5_Rampage_Vice_Point_2() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Chainsaw_Rampage_Vice_Point() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Rocket_Launcher_Rampage_Ocean_Beach() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Minigun_Rampage_Vice_Point() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Pistol_Rampage_Downtown() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Shotgun_Rampage_Escobar_International() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_308_Sniper_Rampage_Vice_Point() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Shotgun_Rampage_Washington_Beach() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_S_P_A_S_12_Rampage_Vice_Point() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_S_P_A_S_12_Rampage_Little_Havana() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_S_P_A_S_12_Rampage_Escobar_International() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Tec_9_Rampage_Washington_Beach() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Katana_Rampage_Escobar_International() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Rampages", "content_lock_rampages"))) end
function rule_Unique_Stunt_Jump_01() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_02() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_03() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_04() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_05() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_06() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_07() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_08() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_09() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_10() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_11() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_12() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_13() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_14() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_15() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_16() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_17() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_18() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_19() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_20() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_21() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_22() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_23() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_24() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_25() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_26() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_27() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_28() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_29() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_30() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_31() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_32() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_33() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_34() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_35() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Unique_Stunt_Jump_36() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles") and lockTerm("Stunt Jumps", "content_lock_stunt_jumps"))) end
function rule_Paramedic_Level_01() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Paramedic_Level_02() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Paramedic_Level_03() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Paramedic_Level_04() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Paramedic_Level_05() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Paramedic_Level_06() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Paramedic_Level_07() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Paramedic_Level_08() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Paramedic_Level_09() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Paramedic_Level_10() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Paramedic_Level_11() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Paramedic_Level_12() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Vigilante_Level_01() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Vigilante_Level_02() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Vigilante_Level_03() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Vigilante_Level_04() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Vigilante_Level_05() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Vigilante_Level_06() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Vigilante_Level_07() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Vigilante_Level_08() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Vigilante_Level_09() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Vigilante_Level_10() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Vigilante_Level_11() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Vigilante_Level_12() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Firefighter_Level_01() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Firefighter_Level_02() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Firefighter_Level_03() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Firefighter_Level_04() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Firefighter_Level_05() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Firefighter_Level_06() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Firefighter_Level_07() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Firefighter_Level_08() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Firefighter_Level_09() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Firefighter_Level_10() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Firefighter_Level_11() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Firefighter_Level_12() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Taxi_Level_01() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Taxi_Level_02() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Taxi_Level_03() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Taxi_Level_04() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Taxi_Level_05() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Taxi_Level_06() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Taxi_Level_07() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Taxi_Level_08() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Taxi_Level_09() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Taxi_Level_10() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Pizza_Level_01() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Pizza_Level_02() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Pizza_Level_03() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Pizza_Level_04() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Pizza_Level_05() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Pizza_Level_06() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Pizza_Level_07() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Pizza_Level_08() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Pizza_Level_09() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Pizza_Level_10() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Hotring() return reachAccess(has("Mainland Access")) end
function rule_Bloodring() return reachAccess(has("Mainland Access")) end
function rule_Dirtring() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Downtown_Chopper_Checkpoint() return reachAccess((has("Mainland Access") and lockTerm("Air Vehicles", "ability_lock_vehicles"))) end
function rule_Ocean_Beach_Chopper_Checkpoint() return reachAccess(lockTerm("Air Vehicles", "ability_lock_vehicles")) end
function rule_Vice_Point_Chopper_Checkpoint() return reachAccess(lockTerm("Air Vehicles", "ability_lock_vehicles")) end
function rule_Little_Haiti_Chopper_Checkpoint() return reachAccess((has("Mainland Access") and lockTerm("Air Vehicles", "ability_lock_vehicles"))) end
function rule_RC_Bandit_Race() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_RC_Baron_Race() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_RC_Raider_Pickup() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Trial_by_Dirt() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_Test_Track() return reachAccess((has("Mainland Access") and lockTerm("Land Vehicles", "ability_lock_vehicles"))) end
function rule_PCJ_Playground() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Cone_Crazy() return reachAccess(lockTerm("Land Vehicles", "ability_lock_vehicles")) end
function rule_Robbable_Store_01() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_02() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_03() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_04() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_05() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_06() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_07() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_08() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_09() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_10() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_11() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_12() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_13() return reachAccess((lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_14() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Robbable_Store_15() return reachAccess((has("Mainland Access") and lockTerm("Weapon Equip", "ability_lock_weapon_equip") and lockTerm("Robbable Stores", "content_lock_robbable_stores"))) end
function rule_Printworks_Purchase() return reachAccess((has("Mainland Access") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Sunshine_Autos_Purchase() return reachAccess((has("Mainland Access") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Film_Studio_Purchase() return reachAccess((has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Cherry_Popper_Purchase() return reachAccess((has("Mainland Access") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Kaufman_Cabs_Purchase() return reachAccess((has("Mainland Access") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Malibu_Club_Purchase() return reachAccess((has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Boatyard_Purchase() return reachAccess((has("Mainland Access") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Pole_Position_Purchase() return reachAccess((has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_El_Swanko_Casa_Purchase() return reachAccess((lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Links_View_Apartment_Purchase() return reachAccess((lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Hyman_Condo_Purchase() return reachAccess((has("Mainland Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Ocean_Heights_Apartment_Purchase() return reachAccess((lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_1102_Washington_Street_Purchase() return reachAccess((lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Vice_Point_Purchase() return reachAccess((lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Skumole_Shack_Purchase() return reachAccess((has("Mainland Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_No_Escape() return reachAccess((has("Progressive Malibu Club") and has("Malibu Club Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_The_Shootist() return reachAccess((itemAtLeast("Progressive Malibu Club", 2) and has("Malibu Club Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_The_Driver() return reachAccess((itemAtLeast("Progressive Malibu Club", 3) and lockTerm("Land Vehicles", "ability_lock_vehicles") and has("Malibu Club Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_The_Job() return reachAccess((itemAtLeast("Progressive Malibu Club", 4) and has("Malibu Club Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Recruitment_Drive() return reachAccess((has("Progressive Film Studio") and has("Film Studio Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Dildo_Dodo() return reachAccess((itemAtLeast("Progressive Film Studio", 2) and lockTerm("Air Vehicles", "ability_lock_vehicles") and has("Film Studio Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Martha_s_Mug_Shot() return reachAccess((itemAtLeast("Progressive Film Studio", 3) and has("Film Studio Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_G_spotlight() return reachAccess((itemAtLeast("Progressive Film Studio", 4) and lockTerm("Land Vehicles", "ability_lock_vehicles") and has("Film Studio Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Spilling_the_Beans() return reachAccess((has("Mainland Access") and has("Progressive Printworks") and has("Printworks Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Hit_the_Courier() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Printworks", 2) and has("Printworks Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_V_I_P() return reachAccess((has("Mainland Access") and has("Progressive Kaufman Cabs") and has("Kaufman Cabs Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Friendly_Rivalry() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Kaufman Cabs", 2) and has("Kaufman Cabs Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Cabmaggedon() return reachAccess((has("Mainland Access") and itemAtLeast("Progressive Kaufman Cabs", 3) and has("Kaufman Cabs Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Distribution() return reachAccess((has("Mainland Access") and has("Progressive Cherry Popper") and has("Cherry Popper Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Checkpoint_Charlie() return reachAccess((has("Mainland Access") and has("Progressive Boatyard") and lockTerm("Sea Vehicles", "ability_lock_vehicles") and has("Boatyard Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
function rule_Sunshine_Autos_Races() return reachAccess((has("Mainland Access") and has("Progressive Sunshine Autos") and lockTerm("Land Vehicles", "ability_lock_vehicles") and has("Sunshine Autos Ownership") and has("Progressive Vercetti Protection") and has("Starfish Island Access") and lockTerm("Wallet", "ability_lock_wallet") and lockTerm("Property Purchases", "content_lock_properties"))) end
