"""Check world positions, generated by scripts/dump_check_coords.py.

Each entry is the game position the PopTracker pack pins a check at. Missions
carry their launcher's trigger position, rampages their pickup, purchases their
for-sale icon, stores their robbery trigger, and side events their launcher.

Three classes are absent. Hidden packages have their positions in the world's
own package_data.py, in the same order, so the generator reads them from there.
Emergency vehicle milestones have no position at all, and stunt jumps are
exe-native, so neither is pinned.

Indexed classes are lists in check order, the order that fixes location ids and
names; the rest are keyed by check name. A 2d position test names no height, so
some heights read as zero; the pins use only x and y.
"""

from __future__ import annotations

MISSION_COORDS: dict[str, tuple[float, float, float]] = {
    "All Hands On Deck!": (-246.6, -1360.5, 7.3),
    "Alloy Wheels of Steel": (-597.3, 652.9, 10.0),
    "An Old Friend": (209.5, -1288.9, 12.4),
    "Autocide": (38.244, -1024.251, 9.451),
    "Back Alley Brawl": (119.2, -826.9, 9.7),
    "Bar Brawl": (-397.4, -561.3, 18.7),
    "Bombs Away!": (-962.4, 143.0, 8.2),
    "Boomshine Saigon": (-1101.1, 343.2, 10.2),
    "Cabmaggedon": (-1003.1, 207.0, 10.0),
    "Cannon Fodder": (-1170.0, -606.9, 10.6),
    "Cap the Collector": (-1062.6, -278.8, 11.0),
    "Check Out at the Check In": (-1481.8719, -825.3049, 13.8777),
    "Checkpoint Charlie": (-585.8, -1506.8, 5.0),
    "Cop Land": (-348.5, -541.8, 16.4),
    "Death Row": (491.0, -77.7, 10.4),
    "Demolition Man": (257.1, -231.7, 10.0),
    "Dildo Dodo": (-69.4, 932.7, 9.9),
    "Dirty Lickin's": (-962.4, 143.0, 8.2),
    "Distribution": (-865.9, -571.9, 11.0),
    "Four Iron": (257.1, -231.7, 10.0),
    "Friendly Rivalry": (-1003.1, 207.0, 10.0),
    "G-spotlight": (-69.4, 932.7, 9.9),
    "Guardian Angels": (-246.6, -1360.5, 7.3),
    "Gun Runner": (-1101.1, 343.2, 10.2),
    "Hit the Courier": (-1062.6, -278.8, 11.0),
    "Hog Tied": (-597.3, 652.9, 10.0),
    "Juju Scramble": (-962.4, 143.0, 8.2),
    "Jury Fury": (119.2, -826.9, 9.7),
    "Keep Your Friends Close...": (-378.3, -579.8, 24.5),
    "Loose Ends": (-978.0145, -530.7043, 9.9513),
    "Love Juice": (-875.5, 1159.3, 10.2),
    "Mall Shootout": (-246.6, -1360.5, 7.3),
    "Martha's Mug Shot": (-69.4, 932.7, 9.9),
    "Messing with the Man": (-597.3, 652.9, 10.0),
    "Naval Engagement": (-1170.0, -606.9, 10.6),
    "No Escape?": (463.9, -58.5, 10.5),
    "Phnom Penh '86": (-378.5, -551.3, 18.2),
    "Psycho Killer": (-875.5, 1159.3, 10.2),
    "Publicity Tour": (-875.5, 1159.3, 10.2),
    "Recruitment Drive": (-69.4, 932.7, 9.9),
    "Riot": (119.2, -826.9, 9.7),
    "Road Kill": (36.798, -1024.4041, 9.451),
    "Rub Out": (-244.6, -491.3, 10.6),
    "Shakedown": (-378.3, -579.8, 24.5),
    "Sir, Yes Sir!": (-246.6, -1360.5, 7.3),
    "Spilling the Beans": (-1062.6, -278.8, 11.0),
    "Stunt Boat Challenge": (-1170.0, -606.9, 10.6),
    "Sunshine Autos Races": (-967.705, -827.3005, 5.7702),
    "Supply & Demand": (-378.5, -551.3, 18.2),
    "The Chase": (-378.5, -551.3, 18.2),
    "The Driver": (463.9, -58.5, 10.5),
    "The Fastest Boat": (-378.5, -551.3, 18.2),
    "The Job": (463.9, -58.5, 10.5),
    "The Party": (119.2, -826.9, 9.7),
    "The Shootist": (463.9, -58.5, 10.5),
    "Treacherous Swine": (-246.6, -1360.5, 7.3),
    "Trojan Voodoo": (-1170.0, -606.9, 10.6),
    "Two Bit Hit": (257.1, -231.7, 10.0),
    "V.I.P.": (-1003.1, 207.0, 10.0),
    "Waste the Wife": (482.5293, 244.276, 10.09),
}

RAMPAGE_COORDS: list[tuple[float, float, float]] = [
    (218.22, -1613.76, 11.06),
    (-1435.29, -833.645, 30.0599),
    (234.86, 34.22, 9.98),
    (479.69, 1110.1801, 17.33),
    (370.63, 1125.86, 26.5),
    (144.449, -545.234, 14.751),
    (-1100.625, 1453.4301, 8.73),
    (-908.317, 744.149, 11.092),
    (-508.768, 1149.203, 18.172),
    (-789.41, 592.56, 11.1),
    (-1011.37, -170.64, 10.99),
    (68.702, -1119.231, 10.458),
    (85.623, -1259.86, 17.092),
    (-679.66, -419.712, 10.469),
    (-1176.3409, -702.975, 22.662),
    (-626.642, -1354.85, 16.373),
    (-1519.33, -292.236, 14.86),
    (-956.113, -1206.33, 14.86),
    (-890.184, -489.655, 36.2),
    (3.426, -1147.0, 10.45),
    (468.656, -1608.79, 11.03),
    (587.795, 1206.26, 15.64),
    (300.673, 1324.88, 22.919),
    (217.247, 261.372, 8.71),
    (-366.44, -1742.1, 11.426),
    (-448.796, 1249.27, 11.75),
    (-674.22, 1162.7, 28.15),
    (-1143.48, -410.87, 10.95),
    (624.26, -230.158, 23.915),
    (-34.13, -948.707, 21.772),
    (593.315, -352.826, 13.711),
    (-1234.83, -90.378, 11.43),
    (-1483.47, -881.677, 14.87),
    (-194.701, -1085.067, 15.66),
    (-983.373, -353.997, 13.84),
]

PROPERTY_COORDS: dict[str, tuple[float, float, float]] = {
    "1102 Washington Street Purchase": (88.5, -804.7, 11.2),
    "Boatyard Purchase": (-685.8, -1495.6, 12.5),
    "Cherry Popper Purchase": (-864.3, -576.6, 11.0),
    "El Swanko Casa Purchase": (428.4, 605.9, 12.2),
    "Film Studio Purchase": (15.2, 962.6, 10.9),
    "Hyman Condo Purchase": (-834.8, 1306.9, 11.0),
    "Kaufman Cabs Purchase": (-1011.7, 203.9, 11.2),
    "Links View Apartment Purchase": (304.5, 376.3, 12.7),
    "Malibu Club Purchase": (487.2, -81.5, 11.4),
    "Ocean Heights Apartment Purchase": (14.0, -1500.7, 12.7),
    "Pole Position Purchase": (99.5, -1468.5, 9.9),
    "Printworks Purchase": (-1059.6, -274.5, 11.4),
    "Skumole Shack Purchase": (-560.1, 703.6, 20.5),
    "Sunshine Autos Purchase": (-1007.3, -869.9, 12.8),
    "Vice Point Purchase": (531.4, 1273.7, 17.6),
}

STORE_COORDS: list[tuple[float, float, float]] = [
    (202.7, -474.1, 10.1),
    (384.04999999999995, 1063.5, 23.05),
    (-967.5, -693.2, 10.3),
    (-859.2, -632.7, 10.6),
    (-854.3, 850.0, 10.6),
    (-830.4, 741.9, 10.6),
    (-846.6, -72.6, 10.8),
    (379.9, 210.2, 10.6),
    (383.2, 759.7, 11.0),
    (449.7, 781.5, 12.2),
    (352.7, 1111.3, 24.5),
    (423.5, 1039.4, 18.1),
    (468.7, 1206.6, 18.2),
    (-1167.5, -613.5, 11.0),
    (-1192.2, -323.7, 11.1),
]

SIDE_EVENT_COORDS: dict[str, tuple[float, float, float]] = {
    "Bloodring": (-1110.3314, 1331.0956, 20.1119),
    "Cone Crazy": (127.5, -1157.5, 30.0),
    "Dirtring": (-1110.3314, 1331.0956, 20.1119),
    "Downtown Chopper Checkpoint": (-569.1451, 851.0923, 22.8402),
    "Hotring": (-1110.3314, 1331.0956, 20.1119),
    "Little Haiti Chopper Checkpoint": (-886.5938, 236.5693, 13.9773),
    "Ocean Beach Chopper Checkpoint": (28.4463, -1311.7614, 16.4712),
    "PCJ Playground": (507.4, -308.8, 13.0),
    "RC Bandit Race": (718.465, 701.3998, 0.0),
    "RC Baron Race": (307.917, 1254.6219, 27.595),
    "RC Raider Pickup": (-1235.1, -1235.7, 0.0),
    "Test Track": (-425.0, 1410.0, 10.5),
    "Trial by Dirt": (-425.0, 1410.0, 10.5),
    "Vice Point Chopper Checkpoint": (375.845, 332.9194, 11.5155),
}

STUNT_JUMP_COORDS: list[tuple[float, float, float]] = [

]
